#!/usr/bin/env bash
# installs nginx and configure it to listens on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R ubuntu:ubuntu /var/www
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
