#!/usr/bin/env bash
# installs nginx and configure it to listens on port 80

sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx restart
