#!/usr/bin/env bash
# installs nginx and configure it to listens on port 80

# updatting
sudo apt -y update
# installing nginx
sudo apt -y install nginx
# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'
# give ownership of the folder www to the user
if [ -d "/var/www" ];
then
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
else
	sudo mkdir -p /var/www
	sudo chown -R "$USER":"$USER" /var/www
	sudo chmod -R 755 /var/www
fi
echo "Hello World!" > /var/www/html/index.html
sudo -i sed '/listen 80 default_server;/i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ];
then
	sudo service nginx start
else
	sudo service nginx restart
fi
