#!/usr/bin/env bash
# installs nginx and configure it to listens on port 80

sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R ubuntu:ubuntu /var/www
echo "Hello World!" > /var/www/html/index.html
sudo -i sed '/listen 80 default_server;/i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart
