#!/usr/bin/env bash
# comment
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt update -y
sudo apt install haproxy -y
sudo printf "\n
	\tbind :80\n
	\tmode http\n
	\tserver 51402-web-01 100.25.191.25:80 check\n
	\tserver 51402-web-02 54.209.27.50:80 check\n
	" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
