#!/usr/bin/env bash
# Indefinitely writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program should pause for 2 seconds

if [[ "$1" -eq "start" ]]
then
	./manage_my_process &
	touch /var/run/my_process.pid && echo $! >> /var/run/my_process.pid
	echo "manage_my_process started"
elif [[ "$1" -eq "stop" ]]
then
	kill $!
	rm -rf /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [[ "$1" -eq "restart" ]]
then
	kill $!
	rm -rf /var/run/my_process.pid
	./manage_my_process &
	touch /var/run/my_process.pid && echo $! >> /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi

