#!/usr/bin/env bash
# install the ufw firewall and setup few rules on web-01
sudo apt install ufw -y
sudo ufw enable
sudo default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
